export const FETCH_BUS_LOCATIONS = 'FETCH_BUS_LOCATIONS';
export const SET_BUS_LOCATIONS = 'SET_BUS_LOCATIONS';

export const SET_FILTERS = 'SET_FILTERS';
export const APPLY_FILTERS = 'APPLY_FILTERS';